### ISSUE TITLE
Unread notifications are hard to distinguish on grayscale

### ISSUE THREAD

**Issue by 7twin** [7twin/devrant-black-theme#2]
If you activate the grayscale option for the theme, the unread notifications are hard to distinguish from the read ones.

Possible fix:
* apply a brightness filter to the read notification icons
* add a 0.5 background to the unread notifications
* ~~change the colors for read notifications to be darker~~

**Comment by devTeaa** [comment]
This actually has been fixed with the latest update.
![capture](https://user-images.githubusercontent.com/38621036/42671550-beb6e644-868a-11e8-9a42-a817ab31fe14.PNG)

**Comment by 7twin** [comment]
@devFreeTea I kept it open, since the other possible fixes mentioned, would be an interesting option to keep in mind still.

**Comment by 7twin** [comment]
@devFreeTea I have edited the issue, to reflect the current state.
