### ISSUE TITLE
Default background colour on post rants type button on greyscale mode

### ISSUE THREAD

**Issue by devTeaa** [7twin/devrant-black-theme#5]
**Describe the bug**
The post rants type button still have the default background, is this meant to be this way?

**To Reproduce**
1. Click on add new rants button '+'
2. The rants type button still have the default background colour

**Expected behavior**
![capture](https://user-images.githubusercontent.com/38621036/42671464-45355ff8-868a-11e8-8333-eb3b6fc6665f.PNG)

**Screenshots**
![capture](https://user-images.githubusercontent.com/38621036/42671156-e096add2-8688-11e8-8cd3-f882353d7917.PNG)

**Desktop (please complete the following information):**
General

**Smartphone (please complete the following information):**
General

**Additional context**
Maybe add a grey variable so it could be used for button? I noticed some greyscale button is a bit transparent, I have edited it on my own script

**Comment by 7twin** [comment]
> The post rants type button still have the default background, is this meant to be this way?

I left it this way as it had something to it visually, but it could be changed to have the same color and hover as e.g. the "comment" button, since greyscale mode probably is expected to do that. I'll review your PR, thanks!
